### ISSUE TITLE
classification and coordinates

### ISSUE THREAD

**Issue by RoyDovrat** [facebookresearch/EasyComDataset#6]
Hi,
We are working on our graduation project, as part of the project we are trying to understand several things in your article. We would be happy if you could answer some questions:
1.What kind of classification do you do, and how did you deal with the large number of classes? Is there use of multi-class-multi-label?
2. How do you deal with the fact that the coordinates are relative to a fixed place in space? (In the article it was written that the coordinates are relative to the left leg of the table). If we assume there is a speaker in a fixed place, we will get a situation where his labeling is fixed, but the array is constantly moving, so the position relative to the array changes (while the labeling remains constant).

**Comment by jdonley** [comment]
Hi @RoyDovrat, 
1. Could you elaborate a little more on the classification you are referring to?
2. The positions and rotations of the participants are global coordinates with an origin that is at the leg of the table as described in the dataset. Which labels are you referring to? I think all the labels provided are associated with a participant ID, which then corresponds to the associated positional data.

**Comment by RoyDovrat** [comment]
Hi, @jdonley 
thanks for the answer. regarding the second question, (following the article "Egocentric Deep Multi-Channel Audio-Visual Active Speaker Localization") we are trying to localize an active speaker using a neural network that receives the audio and video of the Easycom dataset and outputs a 360 degree map . The map indicates where an active speaker is located in relation to the device wearer.
In order to do this we want to label each frame according to the location of the active speakers in the space in relation to the device wearer
However, the location data of the participants is not relative to the device wearer but is fixed in space relative to a fixed point (the leg of the table). How can the locations of the participants be found in relation to the device wearer?

**Comment by jdonley** [comment]
Hi @RoyDovrat, I will do my best to help you here but it is probably best to reach out to the authors of that paper directly. 

In order to get the relative coordinates of the participants from the device wearer, you will need to make the device wearer the new origin in both position and rotation. To do this, you can translate the positions and rotate the rotations so that the origin is at the device wearer and pointing in the same direction. You will likely need to subtract the position and rotate the coordinates in the opposite rotation of the device wearer.
